### PR TITLE
Update beautysh.py

### PR DESCRIPTION
**Pull request by trystero11**
Proposed fix for issue 57 (https://github.com/lovesegfault/beautysh/issues/57). Tested in my local environment and working there.

### CODE REVIEW

**Comment by lovesegfault** [comment]
Thank you so much for your contribution! Could you please add a test so this doesn't regress in the future?

**Comment by lovesegfault** [comment]
Hmm, this seems to just undo #7, which was a fix to #2. It may require some fiddling to make sure both the test cases presented in #2 and #57 work.

**Comment by trystero11** [comment]
Yes, I realised that after submitting the PR. My version fixes the #57 test case, but not the #2 test case. So it seems a more nuanced fix is needed. Sorry…

FWIW, the #2 test's if/elif statement is at the top level of the file, while the #57 test's statement is in a function. I'm seeing the problem in functions, too. So the issue isn't just "elif", it's "elif in a function".

**Comment by trystero11** [comment]
Yeah, I needed to test more. I've added my findings as a comment on #57 and will close this PR. Sorry to waste your time!

**Pull request closed without merging**
